name: Chuck Norris Jokes - workflow 
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:chrome69
    steps: 
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: "Install dependencies"
        run: npm install

      - name: "Production build"
        run: npm run build

      - name: "Run e2e tests"
        run: npm run ci:e2e-tests
      
